ann_bies = {

'ABBREV':'NN',

'ADJ':'JJ',
'ADJ+NSUFF_FEM_DU_ACCGEN':'JJ',
'ADJ+NSUFF_FEM_DU_ACCGEN_POSS':'JJ',
'ADJ+NSUFF_FEM_DU_NOM':'JJ',
'ADJ+NSUFF_FEM_PL':'JJ',
'ADJ+NSUFF_FEM_SG':'JJ',
'ADJ+NSUFF_MASC_DU_ACCGEN':'JJ',
'ADJ+NSUFF_MASC_DU_ACCGEN_POSS':'JJ',
'ADJ+NSUFF_MASC_DU_NOM':'JJ',
'ADJ+NSUFF_MASC_DU_NOM_POSS':'JJ',
'ADJ+NSUFF_MASC_PL_ACCGEN':'JJ',
'ADJ+NSUFF_MASC_PL_ACCGEN_POSS':'JJ',
'ADJ+NSUFF_MASC_PL_NOM':'JJ',
'ADJ+NSUFF_MASC_SG_ACC_INDEF':'JJ',
'ADJ_PROP':'JJ',
'ADJ_PROP+NSUFF_FEM_SG':'JJ',
'ADJ_PROP+NSUFF_MASC_PL_NOM':'JJ',
'ADJ_PROP+NSUFF_MASC_SG_ACC_INDEF':'JJ',

'ADV':'RB',
'ADV+NSUFF_FEM_SG':'RB',
'ADV+NSUFF_MASC_SG_ACC_INDEF':'RB',

'CONJ':'CC',

'CONJ+NEG_PART':'CC-RP',

'DEM_PRON_F':'DT',
'DEM_PRON_FD':'DT',
'DEM_PRON_FS':'DT',
'DEM_PRON_MD':'DT',
'DEM_PRON_MP':'DT',
'DEM_PRON_MS':'DT',
'DET':'DT',

'DET+ADJ':'JJ',
'DET+ADJ+NSUFF_FEM_DU_ACCGEN':'JJ',
'DET+ADJ+NSUFF_FEM_DU_NOM':'JJ',
'DET+ADJ+NSUFF_FEM_PL':'JJ',
'DET+ADJ+NSUFF_FEM_SG':'JJ',
'DET+ADJ+NSUFF_MASC_DU_ACCGEN':'JJ',
'DET+ADJ+NSUFF_MASC_DU_NOM':'JJ',
'DET+ADJ+NSUFF_MASC_PL_ACCGEN':'JJ',
'DET+ADJ+NSUFF_MASC_PL_NOM':'JJ',
'DET+ADJ_PROP':'JJ',
'DET+ADJ_PROP+NSUFF_FEM_SG':'JJ',
'DET+ADJ_PROP+NSUFF_MASC_PL_ACCGEN':'JJ',

'DET+ADV+NSUFF_FEM_SG':'RB',

'DET+NEG_PART':'DT-RP',

'DET+NOUN':'NN',

'DET+NOUN+NSUFF_FEM_DU_ACCGEN':'NNS',
'DET+NOUN+NSUFF_FEM_DU_NOM':'NNS',
'DET+NOUN+NSUFF_FEM_PL':'NNS',

'DET+NOUN+NSUFF_FEM_SG':'NN',

'DET+NOUN+NSUFF_MASC_DU_ACCGEN':'NNS',
'DET+NOUN+NSUFF_MASC_DU_NOM':'NNS',
'DET+NOUN+NSUFF_MASC_PL_ACCGEN':'NNS',
'DET+NOUN+NSUFF_MASC_PL_NOM':'NNS',

'DET+NOUN_PROP':'NNP',

'DET+NOUN_PROP+NSUFF_FEM_PL':'NNPS',

'DET+NOUN_PROP+NSUFF_FEM_SG':'NNP',

'DET+NOUN_PROP+NSUFF_MASC_DU_ACCGEN':'NNPS',
'DET+NOUN_PROP+NSUFF_MASC_PL_ACCGEN':'NNPS',
'DET+NOUN_PROP+NSUFF_MASC_PL_NOM':'NNPS',

'DET+PREP':'DT-IN',

'EMPHATIC_PARTICLE':'RP',
'EXCEPT_PART':'RP',

'FUNC_WORD':'IN',

'FUT+IV1P+VERB_IMPERFECT':'VBP',
'FUT+IV1S+VERB_IMPERFECT':'VBP',
'FUT+IV2MP+VERB_IMPERFECT+IVSUFF_SUBJ:MP_MOOD:I':'VBP',
'FUT+IV2MS+VERB_IMPERFECT':'VBP',
'FUT+IV3FS+VERB_IMPERFECT':'VBP',

'FUT+IV3FS+VERB_PASSIVE':'VBN',

'FUT+IV3MD+VERB_IMPERFECT+IVSUFF_SUBJ:D_MOOD:I':'VBP',
'FUT+IV3MP+VERB_IMPERFECT+IVSUFF_SUBJ:MP_MOOD:I':'VBP',
'FUT+IV3MS+VERB_IMPERFECT':'VBP',

'FUT+IV3MS+VERB_PASSIVE':'VBN',

'INTERJ':'UH',
'INTERJ+NSUFF_MASC_SG_ACC_INDEF':'UH',

'INTERROG_PART':'RP',

'IV1P+VERB_IMPERFECT':'VBP',

'IV1P+VERB_PASSIVE':'VBN',

'IV1S+VERB_IMPERFECT':'VBP',

'IV1S+VERB_PASSIVE':'VBN',

'IV2D+VERB_IMPERFECT+IVSUFF_SUBJ:D_MOOD:I':'VBP',
'IV2FS+VERB_IMPERFECT+IVSUFF_SUBJ:2FS_MOOD:SJ':'VBP',
'IV2MP+VERB_IMPERFECT+IVSUFF_SUBJ:MP_MOOD:I':'VBP',
'IV2MP+VERB_IMPERFECT+IVSUFF_SUBJ:MP_MOOD:SJ':'VBP',
'IV2MS+VERB_IMPERFECT':'VBP',

'IV2MS+VERB_PASSIVE':'VBN',

'IV3FD+VERB_IMPERFECT+IVSUFF_SUBJ:D_MOOD:I':'VBP',
'IV3FD+VERB_IMPERFECT+IVSUFF_SUBJ:D_MOOD:SJ':'VBP',
'IV3FP+VERB_IMPERFECT+IVSUFF_SUBJ:FP':'VBP',
'IV3FS+VERB_IMPERFECT':'VBP',

'IV3FS+VERB_PASSIVE':'VBN',

'IV3MD+VERB_IMPERFECT+IVSUFF_SUBJ:D_MOOD:I':'VBP',
'IV3MD+VERB_IMPERFECT+IVSUFF_SUBJ:D_MOOD:SJ':'VBP',
'IV3MP+VERB_IMPERFECT+IVSUFF_SUBJ:MP_MOOD:I':'VBP',
'IV3MP+VERB_IMPERFECT+IVSUFF_SUBJ:MP_MOOD:SJ':'VBP',

'IV3MP+VERB_PASSIVE+IVSUFF_SUBJ:MP_MOOD:I':'VBN',

'IV3MS+VERB_IMPERFECT':'VBP',

'IV3MS+VERB_PASSIVE':'VBN',

'IVSUFF_DO:1P':'PRP',
'IVSUFF_DO:1S':'PRP',
'IVSUFF_DO:2MP':'PRP',
'IVSUFF_DO:2MS':'PRP',
'IVSUFF_DO:3D':'PRP',
'IVSUFF_DO:3FS':'PRP',
'IVSUFF_DO:3MP':'PRP',
'IVSUFF_DO:3MS':'PRP',

'NEG_PART':'RP',
'NEG_PART+PVSUFF_SUBJ:3MS':'RP',

'NO_FUNC':'NNP',

'NON_ALPHABETIC':'FW',
'NON_ARABIC':'FW',

'NOUN':'NN',

'NOUN+NSUFF_FEM_DU_ACCGEN':'NNS',
'NOUN+NSUFF_FEM_DU_ACCGEN_POSS':'NNS',
'NOUN+NSUFF_FEM_DU_NOM':'NNS',
'NOUN+NSUFF_FEM_DU_NOM_POSS':'NNS',
'NOUN+NSUFF_FEM_PL':'NNS',

'NOUN+NSUFF_FEM_SG':'NN',

'NOUN+NSUFF_MASC_DU_ACCGEN':'NNS',
'NOUN+NSUFF_MASC_DU_ACCGEN_POSS':'NNS',
'NOUN+NSUFF_MASC_DU_NOM':'NNS',
'NOUN+NSUFF_MASC_DU_NOM_POSS':'NNS',
'NOUN+NSUFF_MASC_PL_ACCGEN':'NNS',
'NOUN+NSUFF_MASC_PL_ACCGEN_POSS':'NNS',
'NOUN+NSUFF_MASC_PL_NOM':'NNS',
'NOUN+NSUFF_MASC_PL_NOM_POSS':'NNS',

'NOUN+NSUFF_MASC_SG_ACC_INDEF':'NN',

'NOUN_PROP':'NNP',

'NOUN_PROP+NSUFF_FEM_PL':'NNPS',

'NOUN_PROP+NSUFF_FEM_SG':'NNP',

'NOUN_PROP+NSUFF_MASC_PL_ACCGEN':'NNPS',

'NOUN_PROP+NSUFF_MASC_SG_ACC_INDEF':'NNP',

'NUM':'CD',

'NUMERIC_COMMA':'PUNC',

'PART':'RP',

'POSS_PRON_1P':'PRP$',
'POSS_PRON_1S':'PRP$',
'POSS_PRON_2FS':'PRP$',
'POSS_PRON_2MP':'PRP$',
'POSS_PRON_2MS':'PRP$',
'POSS_PRON_3D':'PRP$',
'POSS_PRON_3FP':'PRP$',
'POSS_PRON_3FS':'PRP$',
'POSS_PRON_3MP':'PRP$',
'POSS_PRON_3MS':'PRP$',

'PREP':'IN',
'PREP+NSUFF_FEM_SG':'IN',
'PREP+NSUFF_MASC_SG_ACC_INDEF':'IN',
'PREP_PROP':'IN',

'PRON':'PRP',
'PRON_1P':'PRP',
'PRON_1S':'PRP',
'PRON_2FS':'PRP',
'PRON_2MP':'PRP',
'PRON_2MS':'PRP',
'PRON_3D':'PRP',
'PRON_3FP':'PRP',
'PRON_3FS':'PRP',
'PRON_3MP':'PRP',
'PRON_3MS':'PRP',

'PVSUFF_DO:1P':'PRP',
'PVSUFF_DO:1S':'PRP',
'PVSUFF_DO:3D':'PRP',
'PVSUFF_DO:3FS':'PRP',
'PVSUFF_DO:3MP':'PRP',
'PVSUFF_DO:3MS':'PRP',
'PVSUFF_SUBJ:1P':'PRP',
'PVSUFF_SUBJ:1S':'PRP',
'PVSUFF_SUBJ:3FS':'PRP',

'REL_ADV':'WRB',

'REL_PRON':'WP',

'REL_PRON+PREP':'WP-IN',

'RESULT_CLAUSE_PARTICLE':'RP',
'SUBJUNC':'RP',

'VERB_PASSIVE':'VBN',
'VERB_PASSIVE+PVSUFF_SUBJ:1S':'VBN',
'VERB_PASSIVE+PVSUFF_SUBJ:3FS':'VBN',
'VERB_PASSIVE+PVSUFF_SUBJ:3MD':'VBN',
'VERB_PASSIVE+PVSUFF_SUBJ:3MP':'VBN',
'VERB_PASSIVE+PVSUFF_SUBJ:3MS':'VBN',

'VERB_PERFECT':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:1P':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:1S':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:2FS':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:2MP':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:3FD':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:3FP':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:3FS':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:3MD':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:3MP':'VBD',
'VERB_PERFECT+PVSUFF_SUBJ:3MS':'VBD'
}
